---
kind: pipeline
type: exec
name: blog

platform:
  os: linux
  arch: amd64

steps:
- name: build_image
  commands:
  - docker build -t mystchen/blog:latest .
- name: restart_container
  commands: 
  - docker container restart blog