---
kind: pipeline
type: docker
name: blog

steps:
- name: build_image  
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: mystchen/blog
    tags: latest
- name: delete_pod
  image: plugins/webhook
  settings:
    urls: 
      from_secret: delete_url
    content_type: application/json
    method: DELETE
- name: create_pod
  image: plugins/webhook
  settings:
    urls: 
      from_secret: create_url
    content_type: application/json
    method: POST
    template: |
      {
          "Image":"mystchen/blog:latest"， # 容器使用镜像 
          "ExposedPorts": {
              "80/tcp": {} # 容器向外曝露的端口
          }，
          "HostConfig": {
              "PortBindings": {
                  "80/tcp": [
                      {
                          "HostPort": "80" 
                      }
                  ]
              }
          }
      }