---
kind: pipeline
type: exec
name: docker-hexo

platform:
  os: linux
  arch: amd64

steps:
- name: remove_container
  failure: ignore
  commands:
  - docker container rm -f blog
- name: start_container
  commands:
  - docker run -d -p 80:80 --name blog mystchen/docker-hexo:latest sh /run.sh